fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.2
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.5.0
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile
      ref: 1.1.2
    postgresql:
      repo: git://github.com/puppetlabs/puppetlabs-postgresql
      ref: 4.6.1
    sudo:
      repo: git://github.com/saz/puppet-sudo.git
      ref: v3.0.6
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
    augeasproviders_core:
      repo: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
      ref: 1.2.4
  symlinks:
    ovirt: "#{source_dir}"
