name    'treydock-ovirt'
version '0.0.1'
source 'git://github.com/treydock/puppet-ovirt.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'oVirt Puppet module'
description 'oVirt Puppet module'
project_page 'http://github.com/treydock/puppet-ovirt'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'puppetlabs/firewall', '1.x'
dependency 'puppetlabs/inifile', '1.x'
dependency 'puppetlabs/postgresql', '3.x'
dependency 'saz/sudo', '3.x'
dependency 'stahnma/epel', '0.x'
